### ISSUE TITLE
Assertion purpose.

### ISSUE THREAD

**Issue by glennmichaelmejias** [MariaMelnik/flutter_date_pickers#2]
What is the purpose of this code?
When I set the firstAllowedDate and selectedPeriod is today, it cause an error.
`assert(selectedPeriod.start.isAfter(firstDate) ||
selectedPeriod.start.isAtSameMomentAs(firstDate)),`

**Comment by MariaMelnik** [comment]
Hi,
this assertion says you can't select date before your first date what is allowable to select.
If you have date picker with start date 05/30/2019 20:29:00 you are not allowed to select anything before it (even 05/30/2019 20:28:00).

By the way, where do you have this error?

**Comment by glennmichaelmejias** [comment]
I haven't selected anything yet. The error comes up during initialization.

I use RangePicker with 

`selectedPeriod = DatePeriod(DateTIme.now(),DateTime.now())`
and
`firstDate = DateTime.now()`

**Comment by MariaMelnik** [comment]
You should save DateTime.now() as a variable and use it when you init firstDate.

You call DateTime.now() 3 times. Every time it returns current time.
In this case firstDate is little bit later (if it goes after selectedPeriod init).
So first date is couple microseconds later start of the selected period. That's why you have assertion.

**Comment by glennmichaelmejias** [comment]
Thanks. I'm so stupid.
