### ISSUE TITLE
How to set monday as a first day of a week?

### ISSUE THREAD

**Issue by miff** [MariaMelnik/flutter_date_pickers#4]
I set it `Intl.defaultLocale = 'en_GB';`, but still nothing

**Comment by MariaMelnik** [comment]
You can specify custom locale in MaterialApp widget (`locale` property).
Otherwise locale from device will be used.
By default only "en_US" locale is supported. If you would like use other you should specify `localizationDelegates` for it in MaterialApp widget. `flutter_localizations` package can help.
Maybe I will add some common locales support by default.

**Comment by parth22** [comment]
how can i disable some dates as you disable in your package.
the below function is disable dates in your package i have some dates that i doesn't want to select the user. it will be very help full for me if you guide me for that.
```
bool _isDisabled(DateTime day) {
    final DateTime beginOfTheFirstDay =
        DateTime(firstDate.year, firstDate.month, firstDate.day);
    final DateTime endOfTheLastDay =
        DateTime(lastDate.year, lastDate.month, lastDate.day + 1)
            .subtract(Duration(microseconds: 1));

    return day.isAfter(endOfTheLastDay) || day.isBefore(beginOfTheFirstDay);

  }
```

**Comment by MariaMelnik** [comment]
@parth22 for now package doesn't provide this functionality.
All dates before start and after end date will be disabled. Otherwise - dates are enabled.
But I have thoughts about add functionality that can help you disable custom dates.

As long as this topic about different case and I answered it I am closing this one. So if you would like you can open new one with feature request.
