### ISSUE TITLE
Can i disable a group of dates? 

### ISSUE THREAD

**Issue by jccd1996** [MariaMelnik/flutter_date_pickers#45]
Hello, in this moment, i only can disable one date with selectableDayPredicate, maybe you have some example with disable a group of dates? Thank you!

**Comment by MariaMelnik** [comment]
@jccd1996 you also can disable many dates with selectableDayPredicate. You should define function which will return true of false. If day should be disabled this function should return false. Otherwise - returns true. 

In example for DayPicker you can find [example](https://github.com/MariaMelnik/flutter_date_pickers/blob/master/example/lib/date_pickers_widgets/day_picker_page.dart#L156) of such function. In this example every Sunday will be disabled (because it has weekday value 6 and function will return false). 

In your case might be appropriate way to have List of all dates you would like to disable and check in predicate if date in the list. If it is - return false (date is disable), otherwise - returns true.
Something like this:
```
  bool _isSelectableCustom (DateTime day) {
    return !disabledDatesList.contains(day);
  }
```
